# Aider Configuration - Agentic Workflow Enforcement

# Read files at startup to understand the workflow
read:
  - AI-WORKFLOW.md
  - ai-assistants/agents/product-owner-agent.md
  - ai-assistants/agents/cost-analyst-agent.md
  - ai-assistants/agents/architect-agent.md
  - ai-assistants/agents/developer-agent.md
  - ai-assistants/agents/it-agent.md
  - ai-assistants/agents/tester-agent.md
  - .github/MULTI_AGENT_REVIEW_GUIDE.md

# Convention file with workflow instructions
conventions: .aider.conventions.md
